In [1]:
!pip install nnfs


[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np   #important for process of vectorisation which allows us to do calculations much faster

In [8]:
'''
Making object for a single layer
'''
class layer:
  def __init__(self,n_input,n_neurons):    #constructor called with parameter as data type layer
    self.weights = np.random.randn(n_input,n_neurons) * 0.01     #create a matrix with entries taken randomly form a normal distribution
    self.biases = np.zeros((1,n_neurons))                        #initialzing the biases as zero
  
  def forward(self,input):
    self.output = np.dot(input,self.weights) + self.biases

'''
Making the ReLU activation function
'''
class Activation_Relu:
  def forward(self,input):
    self.output = np.maximum(0,input)

'''
Making the softmax activation function
'''
class Activation_Softmax:
  def forward(self,input):
    exp_values = np.exp(input - np.max(input,axis = 1,keepdims = True))
    self.output = exp_values / np.sum(exp_values, axis =1, keepdims = True)
  

In [11]:
'''
TESTING
'''
import nnfs
from nnfs.datasets import spiral_data
import numpy as np

nnfs.init()

X, y = spiral_data(samples=5, classes=3)
dense1 = layer(2,3)
activation1 = Activation_Relu()
dense2 = layer(3,3)
activation2 = Activation_Softmax()

# Make a forward pass of our training data through this layer
dense1.forward(X)
# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)
# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)
# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

print(activation2.output[:5])


[[0.33333334 0.33333334 0.33333334]
 [0.33333582 0.33332387 0.33334032]
 [0.33333334 0.33333334 0.33333334]
 [0.3333706  0.33328515 0.33334425]
 [0.33331972 0.3333405  0.33333972]]
